# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print(A)
print(B)
print(A@B)
print(np.dot(A,B))

[[0.71456828 0.94469132 0.18379891]
 [0.76702143 0.26477079 0.94312479]
 [0.15886462 0.06895465 0.42859011]
 [0.24665389 0.68775029 0.6880618 ]
 [0.21175536 0.8573615  0.81925067]]
[[0.08492157 0.77269352]
 [0.1797164  0.01065342]
 [0.29863065 0.50423497]]
[[0.28534677 0.65488431]
 [0.39436629 1.0710497 ]
 [0.15387346 0.33959839]
 [0.35002259 0.54485958]
 [0.41671788 0.58585067]]
[[0.28534677 0.65488431]
 [0.39436629 1.0710497 ]
 [0.15387346 0.33959839]
 [0.35002259 0.54485958]
 [0.41671788 0.58585067]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
array1=np.arange(10)
print(array1)
array1[(array1>3)&(array1<8)] *= -1
print(array1)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [49]:
A1=np.arange(10)
index= (A1>3)&(A1<8)
print(index)
A1[index] = A1[index]*(-1)
print(A1)

[False False False False  True  True  True  True False False]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [50]:
A=np.arange(10)
A[(A>3)&(A<8)] *=-1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


9 ( 0+1+2+3+4-1): 기본 파이썬의 sum => -1이 초기값으로 들어가 같이 계산됨.         
10(0+1+2+3+4): numpy에서의 sum=> sum(a,axis) -1이 축으로 해석됨.(마지막 축)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [53]:
Z=np.arange(9).reshape(3,3)
print(Z)
#legal
print(Z**Z)  #거듭제곱이므로 가능
print(2 << Z >> 2)  #비트 연산
print(Z <- Z)  # 지정하는 것은 불가능.파이썬 문법이 아님. 단, -Z와 Z의 비교로는 가능한 듯.
print(1j*Z) #허수 표현이므로 가능
print(Z/1/1) #가능

#illegal
# Z<Z>Z -> X  # 비교를 연속으로 쓸수는 있지만 이 순서는 올바르지 않은 표현이다!

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
print(np.array(0) / np.array(0))   # 결과 : nan
print(np.array(0) // np.array(0))   # 결과 : 0에 가까운 수
print(np.array([np.nan]).astype(int).astype(float))   # 결과: [아주 큰 음수]

nan
0
[-9.22337204e+18]


<ipython-input-55-f7ed9adf2a23>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))   # 결과 : nan
<ipython-input-55-f7ed9adf2a23>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))   # 결과 : 0에 가까운 수
<ipython-input-55-f7ed9adf2a23>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))   # 결과: [아주 큰 음수]


nan         
0         
error           

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [56]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_value = np.intersect1d(Z1, Z2)  #두 배열의 교집합 원소

print("Z1:", Z1)
print("Z2:", Z2)
print("common_value:", common_value)

Z1: [3 7 2 0 0 9 7 0 1 9]
Z2: [3 8 8 2 4 8 5 6 1 3]
common_value: [1 2 3]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [18]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-18-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [36]:
np.sqrt(-1) #허수 표현 불가능

<ipython-input-36-597592b72a04>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [57]:
np.emath.sqrt(-1) # 허수 표현 가능

1j

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [58]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [60]:
A=np.ones(3)*1
B=np.ones(3)*2
print(A)
print(B)
np.add(A,B,out=B)  #B=A+B
np.divide(A,2,out=A)  #A=A/2
np.negative(A,out=A)  #A=-A
np.multiply(A,B,out=A)  #A=A*B

[1. 1. 1.]
[2. 2. 2.]


array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [24]:
array2=np.random.uniform(0,10,10)
print(array2)
print(array2-(array2%1))
print(array2//1)

[2.31626619 1.57012058 4.59822483 1.74542459 2.54596165 1.98847437
 4.80905775 2.38939455 1.77182753 7.12902679]
[2. 1. 4. 1. 2. 1. 4. 2. 1. 7.]
[2. 1. 4. 1. 2. 1. 4. 2. 1. 7.]


In [61]:
#다른 방법들(참고용)
print(np.floor(array2))
print(array2.astype(int))
print(np.trunc(Z))

[2. 1. 4. 1. 2. 1. 4. 2. 1. 7.]
[2 1 4 1 2 1 4 2 1 7]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
b=np.random.uniform(0,4,25).reshape(5,5)
print(b)

[[3.63722588 0.89550634 2.53660445 0.16014202 3.18772595]
 [3.51046771 1.72759679 2.66338915 1.10248109 1.66667197]
 [1.00463577 0.83651408 0.72352033 1.78349422 2.90724433]
 [0.73163032 2.74635702 2.53710004 3.24193532 0.65638388]
 [0.22656198 1.87768325 0.46076184 2.13290037 0.91874582]]


In [62]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)

Z=np.tile(np.arange(0,5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [28]:
A=np.random.random(10)
print(A)
print(np.sort(A))

[0.23112782 0.71904761 0.79456856 0.8147409  0.06722256 0.26276176
 0.97544405 0.52506795 0.41559412 0.52314041]
[0.06722256 0.23112782 0.26276176 0.41559412 0.52314041 0.52506795
 0.71904761 0.79456856 0.8147409  0.97544405]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [29]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
print(A)
print(B)
print(np.array_equal(A,B))  #또는 np.allclose(A,B)

[1 0 0 0 1]
[1 1 0 1 0]
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [30]:
C=np.random.random((10,2))
X,Y=C[:,0],C[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.87252141 0.94751259 0.68551852 0.95396621 0.27015212 0.92168861
 0.70197055 0.31461745 0.03903657 0.5906495 ]
[1.27362531 0.37563334 1.35818061 0.89942807 1.46764187 0.07889301
 0.04459063 0.91546233 0.25563139 0.66104119]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [31]:
Z=np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.97868759 0.74155498 0.50880443 0.83383599 0.14208001 0.35879408
 0.1532593  0.96382212 0.97510917 0.34850183]
[0.         0.74155498 0.50880443 0.83383599 0.14208001 0.35879408
 0.1532593  0.96382212 0.97510917 0.34850183]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [63]:
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()  #Z-v의 절댓값 array의 가장 작은 값의 index 저장. 즉 Z와 v가 가장 가까운 index
print(Z[index])

29


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [65]:
Z=np.arange(9).reshape(3,3)
#방법1
for index,value in np.ndenumerate(Z):
    print(index,value)

print()

#방법2
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [67]:
n=10 #nxn
p=9 #개수
Z=np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),99)
print(Z)

[[ 0.  0.  0.  0. 99.  0.  0.  0.  0.  0.]
 [99.  0.  0.  0.  0.  0.  0.  0.  0. 99.]
 [ 0.  0.  0.  0. 99.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 99. 99.  0.  0.  0.  0.]
 [99.  0.  0. 99. 99.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [73]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print()
print(Z[Z[:,0].argsort()]) #1번째 칼럼의 sort 인덱스 대입

[[4 5 6]
 [0 1 7]
 [8 5 5]]

[[0 1 7]
 [4 5 6]
 [8 5 5]]


In [74]:
# column 2
print(Z)
print()
print(Z[Z[:,1].argsort()]) #2번째 칼럼의 sort 인덱스 대입

[[4 5 6]
 [0 1 7]
 [8 5 5]]

[[0 1 7]
 [4 5 6]
 [8 5 5]]


In [75]:
# column 3
print(Z)
print()
print(Z[Z[:,2].argsort()]) #3번째 칼럼의 sort 인덱스 대입

[[4 5 6]
 [0 1 7]
 [8 5 5]]

[[8 5 5]
 [4 5 6]
 [0 1 7]]
