1. 파이썬 머신러닝 완벽가이드 ch2. 1~ 4/ pg. 85~ 115

### **[개념정리]**


#**CHAPTER 2**
---
### **01. 사이킷런 소개**
사이킷런(scikit-learn): 가장 많이 사용되는 파이썬 머신러닝 라이브러리
- pip install -U scikit-learn: 최신 버전 업데이트

### **02. 첫 머신러닝 - 붓꽃 품종 예측**
붓꽃 데이터 세트로 붓꽃 품종을 분류해보기.
- 분류(Classification): 대표적 지도학습 방법
- 지도학습: 레이블 데이터(정답 주어진 데이터)로 모델을 학습한 후 별도의 테스트 세트에서 미지의 정답 레이블을 예측하는 방식.
- 학습데이터세트(학습용)/테스트데이터세트(예측 성능 평가용)
- sklearn.datasets: 자체 제공 데이터 세트 생성 / sklearn.tree: 트리 기반 ML 알고리즘 구현/ sklearn.model_selection: 학습, 검증, 예측 데이터로 분리, 최적의 하이퍼 파라미터로 평가 위한 모듈 모임
- 하이퍼 파라미터: 직접 입력하는 파라미터, 알고리즘 성능 튜닝 가능

load_iris로 데이터 세트 생성, ML 알고리즘: 의사결정 트리 이용=> DecisionTreeClassifier

- train_test_split(): 데이터 세트를 학습 데이처와 테스트 데이터로 분리, sklearn.model_selection에서 임포트
  - 학습데이터로 모델을 학습시킨 후, 데이스 데이터로 학습 모델의 성능을 평가
  - test_size=0.2: 전체 데이터에서 테스트 데이터 20%, 학습 데이터 80%으로 분할
  - train_test_split(피처 데이터 세트, 레이블 데이터 세트, test_size=)
  - X_train: 학습용 피처 데이터 세트 / X_test: 테스트용 피처 데이터 세트 / y_train: 학습용 레이블 데이터 세트/ y_train: 테스트용 레이블 데이터 세트
- label(target: 예측할 특징)은 0,1,2로 저장, 각각 다른 품종을 의미

**분류 예측 프로세스:**
> 1. DecisionTreeClassifier 객체 생성(dt_clf)
1. 학습 수행: dt_clf.fit(X_train, y_train)
1. 예측 수행(테스트 데이터): dt_clf.predict(X_test)
1. 평가(정확도 측정):accuracy_score(y_test, pred)





### **03. 사이킷런 기반 프레임워크**
(1) Estimator 이해
- 사이킷런은 지도학습(분류, 회귀)의 다양한 알고리즘을 구현, fit(), predict()만으로 학습과 예측 결과 반환
-  Estimator 클래스(지도학습 클래스 통칭)= 분류 알고리즘 구현 클래스: Classifier + 회귀 알고리즘 구현 클래스: Regressor
- fit(), predict() 내부 구현
- cross_val_score()(evaluation함수), 하이터 파라미터 튜닝 지원 클래스(예, GridSearchCV)에서 Estimator을 인자로 받아 평가하거나 하이터파라미터 튜닝 수행

- 비지도 학습(차원 축소, 클러스터링, 피처 추출) 구현 클래스: fit()-데이터 변환을 위한 사전 구조 맞추기, transform()-피처 추출 등의 실제 작업, fit_transform()-하나로 결합

(2) 사이킷런 주요 모듈
- 예제 데이터: sklearn.dataset
- 피처 처리: sklearn.preprocessing, sklearn.feature_selection, sklearn.feature_extraction
- 피처 처리& 차원축소: sklearn.decomposition
- 데이터 분리, 검증&파라미터 튜닝: sklearn.model_selection
- 평가: sklearn.metrics
- ML 알고리즘: sklearn.ensemble, sklearn.linear_model, sklearn.naive_bayes, sklearn.neighbors, sklearn.svm, sklearn.tree, sklearn.cluster
- 유틸리티: sklearn.pipeline

*머신러닝 모델 구축 주요 프로세스*
1. 피처 처리- 피처의 가공, 변경, 추출 수행
2. ML 알고리즘 학습/예측 수행
3. 모델 평가

(3) 내장된 예제 데이터 세트
- datasets.load_boston()/breast_cancer()/diabetes()/digits()/iris()
- fetch(내려받는 데이터): fetch_covtype()/20newsgroups()/olivetti_faces()/1fw_people()/1fw_pairs()/rcv1/m1data()
- 표본 데이터 생성기: datasets.make_classifications()-분류/make_bolbs()-클러스터링
- 일반적으로 딕셔너리 형태, 키는 data, target, target_names, feature_names(리스트 타입), DESCR(스트링 타입)
 - load_iris: class'sklearn.utils.Bunch'
 - .keys()-키들 확인/.data()-피처 데이터 확인
 - .feature_names(리스트)/.target_names(넘파이)/.data(넘파이)/.target(넘파이)



### **04. Model Selection 모듈 소개**
sklearn.model_selection        
(1) 학습/테스트 데이터 세트 분리
- 학습과 예측을 동일한 데이터 세트로 수행하면 예측 정확도가 100%. 따라서 예측은 다른 테스트 전용 데이터 세트로 해야함.
- train_test_split( 피처 데이터 세트, label 데이터 세트, 여러 파라미터...)
  - test_size: 테스트 데이터 크기
  - train_size: 학습 데이터 크기
  - shuffle: 분리 전 섞을지
  - random_state: 난수값 지정
  - 튜플 형태 반환
- .fit(X_train, y_train), .predict(X_test), accuracy_score(y_test, pred)

(2) 교차 검증
- 과적합(Overfitting), 성능 저하 문제-> 교차 검증으로 다양한 학습, 평가 수행
- 1차 교차검증 기반 평가, 2차 테스트 데이터로 평가 : 테스트 데이터셋 외 별도의 검증 데이터 사용(학습 데이터 셋에서 검증 데이터 셋을 추출)

*K 폴드 교차 검증*     
- K개의 데이터 폴드 세트를 만든 후 K번만큼 각 세트에 학습, 검증평가 반복 수행
- k=5일때: 5개의 폴드 데이터에서 각각 하나씩 검증세트일때의 학습, 검증 수행해 총 5개(K개)의 예측 평가를 구하고 평균냄 ==> 평가 결과
```
from sklearn.model_selection import KFold
KFold(n_splits=5) #k값 지정
```
- Stratified K 폴드: 불균형한 분포도(특정 레이블이 매우 많거나 적은)를 가진 레이블 데이터 집합을 위한 K폴드 방식.
  - 원본 데이터의 레이블 분포를 먼저 고려 후, 동일하게 학습/검증 데이터 셋 분배.
  - 회귀는 지원 안됨. 연속형 숫자값이므로 의미 없음
```
skf = StratifiedKFold(n_splits=3)
skf.split(iris_df, iris_df['label']) #레이블 데이터 세트가 인자로 필요
```

- cross_val_score(): 과정을 한번에 수행( 1.폴드 세트 설정, 2. for 루프로 학습/테스트 데이터 인덱스 반복 추출 3. 반복 학습, 예측 수행, 예측 성능 반환)
 - 내부적으로 StratifiedKFold 이용
> cross_val_score(estimator, X, y=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')
  - estimator: 분류/회귀 클래스
  - X= 피처 데이터 세트
  - y= 레이블 데이터 세트
  - scoring = 예측 성능 평가 기술('accuracy')
  - cv= 교차 검증 폴드 수
 - cv만큼 scoring파라미터로 평가 결괏값 배열로 반환

(3) GridSearchCV
- GridSearchCV API로 파라미터 입력, 파라미터 집합을 만들고 순차 적용하며 최적화 진행
- 교차검증 기반으로 순차적으로 파라미터의 최적 값을 찾음
- 수행시간 오래걸림
- cv=3이면 개별 파라미터 조합마다 3개의 폴딩세트를 3회에 걸쳐 학습/평가해 성능 측정
- estimator, param_grid, scoring, cv, refit(=True면 최적의 파라미터 저장)
- 딕셔너리 형태로 key에 하이퍼 파라미터 명칭, list로 파라미터 값 설정
- 일반적으로 GridSearchCV로 최적의 파라미터를 튜닝한 후 별도의 테스트 세트에서 평가함


### **[코드 필사]**

In [2]:
import sklearn
print(sklearn.__version__)

1.5.2


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [5]:
iris = load_iris()
iris #data와 target으로 이루어진 데이터 세트

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
import pandas as pd

#iris 데이터 가져오기
iris=load_iris()

#iris.data는 iris 데이터 세트에서 피처만으로 된 데이터를 numpy로 가지고 있음.
iris_data=iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블 데이터를 numpy로 가지고 있음
# target_names는 target=0,1,2가 각각 가지는 이름들을 저장
iris_label=iris.target
print('iris target값', iris_label)
print('iris target명', iris.target_names)

#데이터 세트를 살펴보기 위해DataFrame으로 변환
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)



iris target값 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명 ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  label
0                5.1               3.5                1.4               0.2      0
1                4.9               3.0                1.4               0.2      0
2                4.7               3.2                1.3               0.2      0

In [8]:
X_train, X_test, y_train, y_test=train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [9]:
dt_clf = DecisionTreeClassifier(random_state=11)
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [10]:
# 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:0.9333


In [12]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [13]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [14]:
print('\n feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print('target의 shape:', iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 

04.

In [16]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터로 예측 수행-> 정확도 100
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))

예측 정확도: 1.0


In [17]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

iris = load_iris()
dt_clf = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [18]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트
kfold= KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [20]:
n_iter=0

# KFold 객체의 split() 호출로 학습, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1
  # 반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size= X_train.shape[0]
  test_size= X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
        .format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


In [24]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [26]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64


In [27]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [28]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

for train_index, test_index in skfold.split(features, label):
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  n_iter += 1
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print(n_iter, accuracy, train_size, test_size)
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))

1 0.98 100 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 0.94 100 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 0.98 100 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


In [33]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도로 하고, 교차 검증 세트는 3개로 한다.
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [34]:
grid_parameters = {'max_depth': [1,2,3],
                   'min_samples_split': [2,3]}

In [35]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

# 딕셔너리 형태로 설정!
parameters = {'max_depth': [1,2,3], 'min_samples_split': [2,3]}

In [36]:
import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

In [39]:
# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가하기
grid_dtree.fit(X_train, y_train)

# df로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  ...  split1_test_score  split2_test_score
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000  ...                0.7               0.70
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000  ...                0.7               0.70
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333  ...                1.0               0.95
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333  ...                1.0               0.95
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000  ...                1.0               0.95
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000  ...                1.0               0.95

[6 rows x 6 columns]

In [41]:
print('GridSeachCV 최적의 파라미터', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도', grid_dtree.best_score_)

GridSeachCV 최적의 파라미터 {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도 0.975


In [42]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# best_estimator_는 이미 최적학습이 됐으므로 별도 학습 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667
